[project]
name = "PSP"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.protection-shield]
path = "contracts/protection-shield.clar"
depends_on = []
